version: '3.7'

services:
  streamlit-app:
    build:
      context: .
    image: data-analysis-chatbot:latest
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - .:/app
    restart: unless-stopped
